function handleError(err: Record<string, unknown>) {
  console.log('Что-то пошло не так', err);
}

export {
  handleError,
};
